name: github-actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository onto the runner to run scripts or other actions against the code (such as build and test tools)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the specified version of the Node.js
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build site
        run: |
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out"

  deploy:
    # Add a dependency to the build job
    needs: build

    # Specify runner + deployment step
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
